# Generated by Django 6.0.2 on 2026-04-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('key_points', models.TextField(blank=True)),
                ('tone', models.CharField(default='urgency', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
