# Generated by Django 6.0.2 on 2026-04-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_extra_requirements_productimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating_script', 'Generating Script'), ('awaiting_script_approval', 'Awaiting Script Approval'), ('generating_video', 'Generating Video'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=30),
        ),
    ]
