# Generated by Django 6.0.2 on 2026-04-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
