# Generated by Django 6.0.2 on 2026-04-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook', models.TextField()),
                ('full_text', models.TextField()),
                ('hook_score', models.FloatField(default=0)),
                ('hashtags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_order', models.IntegerField()),
                ('text', models.TextField()),
                ('duration', models.IntegerField(default=3)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scripts.script')),
            ],
        ),
    ]
